JDP190803-16 - add Order Entity test
interceptor2048/project-jdp-1908-03 pull request #12
Opened 2019-08-27 23:37 UTC by paweltmurawski

2019-08-28 19:38 UTC, kamisc commented
Na razie testy encji Order nie mają sensu, ponieważ encja Order jeszcze nie została zaakceptowana. Zachęcam do zrobienia review. ;-) To jest ten pull request, gdzie nie dałem numeru z jiry.

2019-08-30 14:56 UTC, jtomaszk commented on src/test/java/com/kodilla/ecommercee/repository/OrderRepositoryTest.java
> +public class OrderRepositoryTest {
jeszcze przydałby się test na kasowanie

2019-09-03 18:17 UTC, kamisc requested changes

2019-09-03 18:17 UTC, kamisc commented on src/test/java/com/kodilla/ecommercee/repository/OrderRepositoryTest.java
> +
Brakuje testów na read i update.

2019-09-04 16:39 UTC, kamisc approved these changes

2019-09-05 14:37 UTC, sloenthran approved these changes

2019-09-05 14:37 UTC, sloenthran commented on src/test/java/com/kodilla/ecommercee/repository/OrderRepositoryTest.java
> +        assertEquals(null, deletedRepository);
Polecam taką fajną rzecz w Junit4 jak "assertNull" ;)

2019-09-05 14:38 UTC, merged